- name: "configure server to run rke"
  hosts: localhost
  vars: 
    packages: 
    - wget
    - bash-completion
    - git
    - rsync
    - docker.io
    kernelmodules:
    - br_netfilter 
    - ip6_udp_tunnel 
    - ip_set 
    - ip_set_hash_ip 
    - ip_set_hash_net 
    - iptable_filter 
    - iptable_nat 
    - iptable_mangle 
    - iptable_raw 
    - nf_conntrack_netlink 
    - nf_conntrack 
    - nf_conntrack_ipv4   
    - nf_defrag_ipv4 
    - nf_nat 
    - nf_nat_ipv4 
    - nf_nat_masquerade_ipv4 
    - nfnetlink 
    - udp_tunnel 
    - veth 
    - vxlan 
    - x_tables 
    - xt_addrtype 
    - xt_conntrack 
    - xt_comment 
    - xt_mark 
    - xt_multiport 
    - xt_nat 
    - xt_recent 
    - xt_set  
    - xt_statistic 
    - xt_tcpudp
  tasks:
  - name: "create private Key for rke and Kubernetes"
    command: ssh-keygen -q -t rsa -f ./files/rke -C "" -N ""
    args:
      creates: ./files/rke.pub
  - name: "add pubkey to root"
    authorized_key:
      user: root
      key: "{{ lookup('file', './files/rke.pub') }}"
  - name: "load kernel modules"
    modprobe:
      name: "{{ item }}"
    with_items: "{{ kernelmodules }}"
  - name: "install packages"
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ packages }}"     
  - name: 
    get_url:
      url: https://github.com/rancher/rke/releases/download/v0.3.2/rke_linux-amd64
      dest: /usr/local/bin/rke
      mode: '0744'
  - name: "create docker systemctl directory"
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      mode: 0755
    notify: "restart docker daemon"
  - name: "disable swap"
    mount:
      name: swap
      fstype: swap
      state: absent
  - name: "sysctl"
    sysctl: 
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present
  - name: "ensure docker is started"
    service:
      name: docker
      state: started
      enabled: yes
  - name: "create etcd-snapshots directory"
    file:
      path: /opt/rke/etcd-snapshots
      state: directory
      mode: 0755
 # - name: "Install Kubernetes"
 #   command: /usr/local/bin/rke up --config ./files/cluster.yml
  - name: "Install kubectl"
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl
      dest: /usr/local/bin/kubectl
      mode: '0744'
  - name: "create kubectl config folder"
    file: 
      path: /root/.kube/
      state: directory
  - name: "Copy kubectl config"
    copy:
      src: ./files/kube_config_cluster.yml
      dest: /root/.kube/config
  handlers:
  - name: "restart docker daemon"
    shell: systemctl daemon-reload && systemctl restart docker.service
